### ISSUE TITLE
Export Android Studio Source Code Error

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1370]
Export Android Studio Source codes has some errors. Check below :

![Screenshot_20241109-233320](https://github.com/user-attachments/assets/2e525065-e774-44f7-872b-e94723c943a5)

**Comment by trindadedev13** [comment]
I believe this has been resolved in the latest version, can you try and tell me?

**Comment by AsimJib** [comment]
> I believe this has been resolved in the latest version, can you try and tell me?

I'm using the latest debug version. The problem persist.

![Screenshot_20241110-075022.jpg](https://github.com/user-attachments/assets/da809ba1-505e-422a-a171-bbd7cbacf8c0)

**Comment by trindadedev13** [comment]
no, its not latest, update & try again

**Comment by trindadedev13** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/11761229698

**Comment by AsimJib** [comment]
> https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/11761229698

Thanks for the reference. I'll try it right away.

**Comment by AsimJib** [comment]
> https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/11761229698

Yes, it's fixed on latest version. Thank you. 😊
